[package]
name = "taos-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# backtrace = "0.3"
itertools = "0.10.3"
log = "0.4"
once_cell = "1"
# parking_lot = "0.12.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_with = "1.14.0"
thiserror = "1"
# tungstenite = { version = "0.17", features = ["native-tls-vendored"] }
websocket = "0.26.4"

taos-error = { path = "../taos-error" }
taos-query = { path = "../taos-query", default-features = false }

async-trait = { version = "0.1.56", optional = true }
futures = { version = "0.3", optional = true }
# lockfree = "0.5"
# oneshot = "0.1.3"

scc = "0.8"
tokio = { version = "1", features = ["full"], optional = true }
#tokio-tungstenite = { version = "0.17.1", features = ["__rustls-tls"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls-vendored"], optional = true }

[dev-dependencies]
anyhow = "1"
pretty_env_logger = "*"

[features]
default = [ "async", "stmt", "tmq"]
async = ["async-trait", "tokio", "tokio-tungstenite", "futures", "taos-query/async"]
sync = []
stmt = ["async"]
tmq = ["async"]
