name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TOOLS_BUILD_TYPE: Release
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step that prints name of pull request's base branch
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "Pull request's branch is: ${GITHUB_REF##*/}"
          echo "Pull request's head ref is: ${GITHUB_HEAD_REF}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      - name: Checkout tdengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '3.0'

      - name: Change time zone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo date

      - name: Checkout TDengine's rust connector to PR number
        if: github.event_name == 'pull_request'
        run: |
          sed -E "s/GIT_TAG.*/GIT_TAG ${GITHUB_SHA}/"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build & Install TDengine
        run: |
          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DWEBSOCKET=true && make -j8 || exit 1
          sudo make install
          nohup sudo taosd > /dev/null 2>&1 &
          sleep 5
          nohup sudo taosadapter > /dev/null 2>&1 &

      - name: Run examples
        run: |
          cd TDengine/tools/taosws-rs
          ./taos-ws-sys/ci/package.sh
          cd ./target/libtaosws
          make
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
          ./show-databases || exit 1
